/* Generates js/data/game-config.js from docs/game-spec.json plus facts read from the site
   (library card titles, Guided Study box -> card links).
   Usage: node tools/build-config.js */
"use strict";
var fs = require("fs");
var path = require("path");
var vm = require("vm");

var root = path.join(__dirname, "..");
function read(rel) { return fs.readFileSync(path.join(root, rel), "utf8"); }
var spec = JSON.parse(read("docs/game-spec.json"));

/* Design decisions that the spec states in prose. */
var HEADS_UP = ["w1-l4", "w1-l5", "w7-l5"];
var NO_AUTO_DAILY = ["w1-l4", "w1-l5", "w6-l6", "w7-l3"];
var NO_BOSS_QUESTION = ["w1-l5", "w2-l5", "w3-l4", "w4-l6", "w5-l3", "w6-l4"];
var RULE_CAP = 50;
var DAILY_CAP = 30;
var RUN_SHOWN = 7;

var KIND = {
  "lesson": "lesson", "quiz-perfect": "quiz", "boss": "boss", "sutta-read": "sutta",
  "sutta-check": "suttaq", "rule-read": "rule", "study-check": "study", "journey-read": "jw",
  "theme-read": "theme", "glossary-card": "gloss", "daily-practice": "daily"
};

var xp = { skip: 0 };
spec.xpRules.forEach(function (r) {
  var kind = KIND[r.activity];
  if (!kind) throw new Error("Unknown xp activity: " + r.activity);
  xp[kind] = r.xp;
});
Object.keys(KIND).forEach(function (a) {
  if (xp[KIND[a]] === undefined) throw new Error("Spec has no points rule for: " + a);
});

function rule(b) {
  switch (b.ruleType) {
    case "count": return { type: "count", prefix: b.rulePrefix, n: b.ruleN };
    case "has": return { type: "has", id: b.rulePrefix };
    case "streak": return { type: "streak", n: b.ruleN };
    case "xp": return { type: "xp", n: b.ruleN };
    case "world": return { type: "world", id: b.rulePrefix };
    default: throw new Error("Unknown badge rule type: " + b.ruleType + " (" + b.id + ")");
  }
}

/* "Buddha (say: BOOD-dah) = 'the one who woke up' ..." -> { term, say, old, means } */
function parseTerm(lessonId, keyTerm) {
  var eq = keyTerm.indexOf(" = ");
  if (eq === -1) throw new Error("keyTerm without ' = ' in " + lessonId);
  var head = keyTerm.slice(0, eq);
  var paren = head.indexOf(" (");
  var term = (paren === -1 ? head : head.slice(0, paren)).trim();
  var say = /say:\s*([^,)]+)/.exec(head);
  var old = /old word:\s*([^,)]+)/.exec(head);
  return {
    lesson: lessonId, term: term, say: say ? say[1].trim() : "", old: old ? old[1].trim() : "",
    means: keyTerm.slice(eq + 3).trim()
  };
}

/* Library cards */
var win = {};
var ctx = vm.createContext({ window: win });
["dn", "mn1", "mn2", "sn", "an", "kn"].forEach(function (c) {
  vm.runInContext(read("js/data/suttas-" + c + ".js"), ctx);
});
var cards = {};
win.SUTTAS.forEach(function (s) { cards[s.id] = { ref: s.ref, title: s.title, cat: s.cat }; });

/* Guided Study boxes -> cards */
var study = {};
var studyHtml = read("study.html");
var liRe = /<li><input type="checkbox" data-r="([^"]+)">([\s\S]*?)<\/li>/g, m;
while ((m = liRe.exec(studyHtml))) {
  var ids = [];
  var aRe = /suttas\.html#([^"]+)"/g, a;
  while ((a = aRe.exec(m[2]))) { if (cards[a[1]] && ids.indexOf(a[1]) === -1) ids.push(a[1]); }
  study[m[1]] = ids;
}

var worlds = spec.worlds.slice().sort(function (a, b) { return a.order - b.order; });
var words = [];
worlds.forEach(function (w) {
  w.lessons.forEach(function (l) { if (l.keyTerm && l.keyTerm.trim()) words.push(parseTerm(l.id, l.keyTerm)); });
});

var ranks = spec.ranks.slice().sort(function (a, b) { return a.minXp - b.minXp; }).map(function (r, i) {
  return { index: i, id: r.id, name: r.name, minXp: r.minXp, blurb: r.blurb };
});

var config = {
  ranks: ranks,
  xp: xp,
  caps: { xp: ranks[ranks.length - 1].minXp, rules: RULE_CAP, daily: DAILY_CAP, runShown: RUN_SHOWN },
  badges: spec.badges.map(function (b) { return { id: b.id, name: b.name, how: b.how, rule: rule(b) }; }),
  worlds: worlds.map(function (w) {
    return {
      id: w.id, order: w.order, title: w.title, tagline: w.tagline, stage: w.stage, goal: w.goal,
      bossTitle: w.bossTitle,
      lessons: w.lessons.map(function (l) { return { id: l.id, title: l.title, icon: l.icon, objective: l.objective }; })
    };
  }),
  words: words,
  headsUp: HEADS_UP,
  noAutoDaily: NO_AUTO_DAILY,
  noBossQuestion: NO_BOSS_QUESTION,
  cards: cards,
  study: study,
  streakRule: spec.streakRule,
  dailyPractice: spec.dailyPractice
};

var out = "/* GENERATED by tools/build-config.js from docs/game-spec.json. Do not edit by hand. */\n" +
  "(function (g) { g.GAME_CONFIG = " + JSON.stringify(config, null, 2) +
  "; })(typeof window !== \"undefined\" ? window : global);\n";

fs.writeFileSync(path.join(root, "js", "data", "game-config.js"), out, "utf8");
var lessons = config.worlds.reduce(function (n, w) { return n + w.lessons.length; }, 0);
console.log("Wrote js/data/game-config.js: " + config.worlds.length + " worlds, " + lessons +
  " lessons, " + config.ranks.length + " titles, " + config.badges.length + " badges, " +
  config.words.length + " taught words, " + Object.keys(cards).length + " cards, " +
  Object.keys(study).length + " study boxes.");
words.forEach(function (w) { console.log("  word " + w.lesson + ": " + w.term + (w.old ? " [old: " + w.old + "]" : "") + (w.say ? " (" + w.say + ")" : "")); });
